### ISSUE TITLE
warning message mlDeploy

### ISSUE THREAD

**Issue by DavidEnnis-CleverLlamas** [cleverllamas/marklogic-data-hub#11] opened 2024-06-13 14:11 UTC
gradlew mlDeploy

> Configure project :
Cannot find template location: classpath:/templates/ (please add some templates, check your Groovy configuration, or set spring.groovy.template.check-template-location=false)

**Comment by miguelrgonzalez** [comment] 2024-06-16 16:43
Removing this warning took longer than expected, but I believe it's now fixed.
The root cause was some spring dependencies in the marklogic-data-hub project, which I think were used in the quick-start, that are no longer needed.
I also explicitly excluded groovy-templates from the test dependencies from the plugin (since we don't use them)

Removing these libraries and republishing gets rid of the warning. (verified that tests are 100% passing without them)

**Closed as completed by miguelrgonzalez** 2024-06-16 16:43 UTC
